### ISSUE TITLE
[GDI - ckanext-gdi-userportal] Update GDI User Portal scheme for minimum DCAT-AP "mandatory fields"

### ISSUE THREAD

**Issue by brunopacheco1** [GenomicDataInfrastructure/gdi-userportal-ckanext-gdi-userportal#11]
## What
Update GDI User Portal scheme for minimum DCAT-AP "mandatory fields".

## Why
To have a concise form, that support latest version of DCAT-AP.

## Tasks
- Review DCAT-AP minimum mandatory fields.
- Implement changes.
- Test with Harvester.
- Add tests.

## Acceptance Criteria
- Is there a minimum schema defined for GDI User Portal?
- Is the minimum schema tested with Harvester?

**Comment by hcvdwerf** [comment]
To address this problem in the short term, we are considering using the extra fields. Currently, all fields that are not present are mapped to these extra fields. Ultimately, our goal is to resolve the issue described here: https://github.com/ckan/ckan/issues/7896.

**Comment by brunopacheco1** [comment]
@hcvdwerf for me it's just a matter of simplifying the new dataset view. The current schema has a lot of fields, but I am not sure if all are mandatory fields for DCAT-AP-3.0.

**Comment by brunopacheco1** [comment]
Closing this items as it is not relevant anymore.
