### ISSUE TITLE
[GDI - ckanext-gdi-userportal - SPIKE] How can we optimize endpoints for listing values?

### ISSUE THREAD

**Issue by admy7** [GenomicDataInfrastructure/gdi-userportal-ckanext-gdi-userportal#25]
## What

Currently, there are 5 endpoints allowing to retrieve unique values for different dcat fields:  catalogue_list, keyword_list, theme_list, publisher_list and dataset_list. They are used to display the filter values.

The last three are not optimized and consequently slow.

Propose and implement a better way to fetch the values (better in the sense of shorter retrieval time).

Modify the API calls in the front-end (filters) to reflect the changes.

## Why
To enhance user experience in the front-end.

## Acceptance Criteria
- Retrieval time is almost null, providing a seamless experience in the front-end
- Memory use stays reasonable
- Logic is properly tested

## Tasks
- Find and implement a solution to decrease the data retrieval time.
- Modify the API calls in the front-end (filters) to reflect the changes.
- Implement unit tests

**Comment by brunopacheco1** [comment]
We will create another story for counters

**Comment by brunopacheco1** [comment]
@hcvdwerf 

I was working on fixing the frontend integration with CKAN query, when I found this: https://docs.ckan.org/en/2.10/api/

CKAN already provides an API to get facets values, please check this example: `https://ckan-test.healthdata.nl/api/3/action/package_search?facet.field=%5B"theme"%5D&rows=0`
 
We just need to ensure SOLR indexes multivalued fields (themes) as multivalued in SOLR. Perhaps it's possible to do that with scheming.

**Comment by brunopacheco1** [comment]
https://github.com/ckan/ckanext-scheming/issues/195

**Comment by hcvdwerf** [comment]
Indeed bij fixing the schema I got this 

`{
    "help": "http://localhost:5500/api/3/action/help_show?name=package_search",
    "success": true,
    "result": {
        "count": 907,
        "facets": {
            "theme": {
                "http": 12,
                "org": 12,
                "purl": 12,
                "zonmw": 12,
                "19": 11,
                "covid": 11,
                "httppurlorgzonmwcovid": 11,
                "generic": 10,
                "httppurlorgzonmwgeneric": 10,
                "10": 9,
                "10006": 9,
                "10033": 9,
                "10095": 9,
                "1910033": 9,
                "bioontology": 9,
                "cm": 9,
                "httppurlbioontologyorgontologyicd": 9,
                "icd": 9,
                "ontology": 9,
                "07": 8,
                "071": 8,
                "1": 8,
                "cmu": 8,
                "u": 8,
                "10091": 7,
                "1910006": 7,
                "1910091": 7,
                "10014": 6,
                "1910014": 6,
                "10007": 3,
                "1910007": 3,
                "0853879": 1,
                "10003": 1,
                "10012": 1,
                "10018": 1,
                "10083": 1,
                "10253": 1,
                "10254": 1,
                "1910003": 1,
                "1910012": 1,
                "1910018": 1,
                "1910083": 1,
                "1910253": 1,
                "1910254": 1,
                "2": 1,
                "9245": 1,
                "96": 1,
                "962": 1,
                "c": 1,
                "cmj": 1
            }
        },
        "results": [],
        "sort": "score desc, metadata_modified desc",
        "search_facets": {
            "theme": {
                "title": "theme",
                "items": [
                    {
                        "name": "zonmw",
                        "display_name": "zonmw",
                        "count": 12
                    },
                    {
                        "name": "u",
                        "display_name": "u",
                        "count": 8
                    },
                    {
                        "name": "purl",
                        "display_name": "purl",
                        "count": 12
                    },
                    {
                        "name": "org",
                        "display_name": "org",
                        "count": 12
                    },
                    {
                        "name": "ontology",
                        "display_name": "ontology",
                        "count": 9
                    },
                    {
                        "name": "icd",
                        "display_name": "icd",
                        "count": 9
                    },
                    {
                        "name": "httppurlorgzonmwgeneric",
                        "display_name": "httppurlorgzonmwgeneric",
                        "count": 10
                    },
                    {
                        "name": "httppurlorgzonmwcovid",
                        "display_name": "httppurlorgzonmwcovid",
                        "count": 11
                    },
                    {
                        "name": "httppurlbioontologyorgontologyicd",
                        "display_name": "httppurlbioontologyorgontologyicd",
                        "count": 9
                    },
                    {
                        "name": "http",
                        "display_name": "http",
                        "count": 12
                    },
                    {
                        "name": "generic",
                        "display_name": "generic",
                        "count": 10
                    },
                    {
                        "name": "covid",
                        "display_name": "covid",
                        "count": 11
                    },
                    {
                        "name": "cmu",
                        "display_name": "cmu",
                        "count": 8
                    },
                    {
                        "name": "cmj",
                        "display_name": "cmj",
                        "count": 1
                    },
                    {
                        "name": "cm",
                        "display_name": "cm",
                        "count": 9
                    },
                    {
                        "name": "c",
                        "display_name": "c",
                        "count": 1
                    },
                    {
                        "name": "bioontology",
                        "display_name": "bioontology",
                        "count": 9
                    },
                    {
                        "name": "962",
                        "display_name": "962",
                        "count": 1
                    },
                    {
                        "name": "96",
                        "display_name": "96",
                        "count": 1
                    },
                    {
                        "name": "9245",
                        "display_name": "9245",
                        "count": 1
                    },
                    {
                        "name": "2",
                        "display_name": "2",
                        "count": 1
                    },
                    {
                        "name": "1910254",
                        "display_name": "1910254",
                        "count": 1
                    },
                    {
                        "name": "1910253",
                        "display_name": "1910253",
                        "count": 1
                    },
                    {
                        "name": "1910091",
                        "display_name": "1910091",
                        "count": 7
                    },
                    {
                        "name": "1910083",
                        "display_name": "1910083",
                        "count": 1
                    },
                    {
                        "name": "1910033",
                        "display_name": "1910033",
                        "count": 9
                    },
                    {
                        "name": "1910018",
                        "display_name": "1910018",
                        "count": 1
                    },
                    {
                        "name": "1910014",
                        "display_name": "1910014",
                        "count": 6
                    },
                    {
                        "name": "1910012",
                        "display_name": "1910012",
                        "count": 1
                    },
                    {
                        "name": "1910007",
                        "display_name": "1910007",
                        "count": 3
                    },
                    {
                        "name": "1910006",
                        "display_name": "1910006",
                        "count": 7
                    },
                    {
                        "name": "1910003",
                        "display_name": "1910003",
                        "count": 1
                    },
                    {
                        "name": "19",
                        "display_name": "19",
                        "count": 11
                    },
                    {
                        "name": "10254",
                        "display_name": "10254",
                        "count": 1
                    },
                    {
                        "name": "10253",
                        "display_name": "10253",
                        "count": 1
                    },
                    {
                        "name": "10095",
                        "display_name": "10095",
                        "count": 9
                    },
                    {
                        "name": "10091",
                        "display_name": "10091",
                        "count": 7
                    },
                    {
                        "name": "10083",
                        "display_name": "10083",
                        "count": 1
                    },
                    {
                        "name": "10033",
                        "display_name": "10033",
                        "count": 9
                    },
                    {
                        "name": "10018",
                        "display_name": "10018",
                        "count": 1
                    },
                    {
                        "name": "10014",
                        "display_name": "10014",
                        "count": 6
                    },
                    {
                        "name": "10012",
                        "display_name": "10012",
                        "count": 1
                    },
                    {
                        "name": "10007",
                        "display_name": "10007",
                        "count": 3
                    },
                    {
                        "name": "10006",
                        "display_name": "10006",
                        "count": 9
                    },
                    {
                        "name": "10003",
                        "display_name": "10003",
                        "count": 1
                    },
                    {
                        "name": "10",
                        "display_name": "10",
                        "count": 9
                    },
                    {
                        "name": "1",
                        "display_name": "1",
                        "count": 8
                    },
                    {
                        "name": "0853879",
                        "display_name": "0853879",
                        "count": 1
                    },
                    {
                        "name": "071",
                        "display_name": "071",
                        "count": 8
                    },
                    {
                        "name": "07",
                        "display_name": "07",
                        "count": 8
                    }
                ]
            }
        }
    }
}`

**Comment by brunopacheco1** [comment]
Indeed something has changed, but it looks like there is something to fix on the indexing part. There are strange strings like `httppurlbioontologyorgontologyicd`, as if it was somehow cleaned - no especial character. We should keep the URI's as they are. In the links I shared they suggest both SOLR schema update and implementing `before_index` hooks.

Another interisting thing about this is we have both `name` and `display_name`, Although it is not multilingual, it supports labels for URI's.

**Comment by brunopacheco1** [comment]
We are replacing all `*_list` endpoints by facets in `package_search`. It seems to have a good performance and returns out of the box the facet's possible values of given query context.
