### ISSUE TITLE
[GDI - ckanext-gdi-userportal] Create endpoints for counting items

### ISSUE THREAD

**Issue by admy7** [GenomicDataInfrastructure/gdi-userportal-ckanext-gdi-userportal#30]
## What

Create endpoints for counting different items: catalogues, keywords, themes, publishers, datasets.

Modify GDI front-end to reflect the changes.

## Why

To retrieve the counts quickly so that they can be displayed in the Home page of the front-end, without any lag for the user.

## Acceptance Criteria

- Retrieval time is almost null, providing a seamless experience in the front-end
- Memory use stays reasonable
- Logic is properly tested

## Tasks
- Create the endpoints
- Modify the API calls in the front-end to reflect the changes
-  Implement unit tests

**Comment by brunopacheco1** [comment]
We are replacing all CKAN endpoints by package_search and for now it seems to have a good performance. Closing this item.
