### ISSUE TITLE
[GDI - ckanext-gdi-userportal - SPIKE] How do we load URI labels into database? 

### ISSUE THREAD

**Issue by brunopacheco1** [GenomicDataInfrastructure/gdi-userportal-ckanext-gdi-userportal#34]
## What
How do we load URI labels into database? Test it with languages.

## Why

So whenever one is editing datasets in CKAN or a harvester is loading a new dataset, we have language labels associate to URI's.

## Tasks
- Create datastore database in Postgres and configure CKAN properly (e.g. https://github.com/ckan/ckan-docker)
- Load [languages.csv](https://github.com/GenomicDataInfrastructure/gdi-userportal-ckan-docker/files/13780768/languages.csv) into datastore

## Acceptance criteria
- Is datastore configured in this project?
- Is loading languages csv documented in gdi-userportal-docs?
- Is the datastore configuration documented in gdi-userportal-docs?

**Comment by a-nayden** [comment]
- datastore allows loading resources only if they are linked to a package. In other words if we want to upload language information we need to do in for each dataset. That is why datastore seems not feasible for implementing language labels.
- in general datastore is not configured for GDI CKAN. If we decide to do so a separate database should be configured and permissions changed as per documentation: https://docs.ckan.org/en/2.9/maintaining/datastore.html#setting-up-the-datastore
- CKAN community suggests to implement several fields on dataset level: https://matrix.to/#/!FWrlEPqVnWhKTQqGjK:gitter.im/$_WJrDRoTDAqQWnOozWdPprXO5oXdzg0S9FPC4k9tOzE?via=gitter.im&via=matrix.org&via=matrix.cuates.net

**Comment by brunopacheco1** [comment]
@a-nayden what is exactly the solution?

**Comment by brunopacheco1** [comment]
If you take few examples, you will see this is not the case. https://data.europa.eu/api/hub/repo/datasets/a96bcef4-e79a-45e1-a927-c71f9c5cf685.ttl?useNormalizedId=true&locale=en

**Comment by brunopacheco1** [comment]
Language labels are not the only URI/labels we need to map: access rights, themes, dataset type and much more other fields must be maps.

**Comment by a-nayden** [comment]
labels may not be in the harvested data but nothing prevents a harvester to fetch a label from an ontology.
Correct - we have to do that for a list of fields.

**Comment by brunopacheco1** [comment]
Before starting any development, please let us discuss all together, to properly prioritise all the deliverables.

Remember that we should find a solution that fits to all problems (text searching, filtering, displaying, and i18n). The suggestion you got from one CKAN guy supports only monolingual displaying and text searching.

Regarding performance:
- extra steps in the harvest to access the URI and fetch labels, for every dataset, every linkable field and every data source.
- While filtering, we need to build a list of all possible values for each field. That will require going through all possible datasets.
- Vocabularies should not change that often to justify fetching them with this regularity.

Another thing to consider is the mantainability of the schema. It looks already complex, and eventually it will grow to fit to other purposes.

In the end, to have a robust solution, we'd need both centralised repository with all terms and labels, and also persist inside the dataset all the labels.
